"""
==========================================================
Metadata Manager
Multimodal Retail Assistant (Myntra AI)
==========================================================

Purpose
-------
Loads the product metadata generated by
metadata_generator.py.

Responsibilities

✔ Load metadata

✔ Retrieve products

✔ Search by ID

✔ Search by Name

✔ Return product documents

This module is used by the RAG engine.

Author: Noira Khan
==========================================================
"""

from pathlib import Path
import json


BASE_DIR = Path(__file__).resolve().parent.parent

METADATA_FILE = BASE_DIR / "docs" / "product_metadata.json"


class MetadataManager:

    def __init__(self):

        self.products = self.load_metadata()

    # ------------------------------------------------------

    def load_metadata(self):

        if not METADATA_FILE.exists():

            raise FileNotFoundError(
                f"Metadata file not found:\n{METADATA_FILE}"
            )

        with open(
            METADATA_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            products = json.load(file)

        print(
            f"Loaded {len(products)} products."
        )

        return products

    # ------------------------------------------------------

    def get_all_products(self):

        return self.products

    # ------------------------------------------------------

    def total_products(self):

        return len(self.products)

    # ------------------------------------------------------

    def get_documents(self):

        return [

            product["document"]

            for product in self.products

        ]

    # ------------------------------------------------------

    def get_product_names(self):

        return [

            product["product_name"]

            for product in self.products

        ]

    # ------------------------------------------------------

    def get_product_by_id(self, product_id):

        for product in self.products:

            if product["id"] == product_id:

                return product

        return None

    # ------------------------------------------------------

    def get_product_by_name(self, name):

        for product in self.products:

            if product["product_name"].lower() == name.lower():

                return product

        return None


# ----------------------------------------------------------
# Testing
# ----------------------------------------------------------

if __name__ == "__main__":

    manager = MetadataManager()

    print()

    print("Total Products")

    print(manager.total_products())

    print()

    print("First Product")

    print(manager.get_all_products()[0])